#ifndef GAUSSIAN_SPLAT_COMMON_USH
#define GAUSSIAN_SPLAT_COMMON_USH

float3x3 CalcMatrixFromRotationScale(float4 Rot, float3 Scale)
{
    float x = Rot.x;
    float y = Rot.y;
    float z = Rot.z;
    float w = Rot.w;

    float3x3 Ms = float3x3(
        Scale.x, 0, 0,
        0, Scale.y, 0,
        0, 0, Scale.z);

    float3x3 Mr = float3x3(
        1 - 2 * (y * y + z * z), 2 * (x * y - w * z),     2 * (x * z + w * y),
        2 * (x * y + w * z),     1 - 2 * (x * x + z * z), 2 * (y * z - w * x),
        2 * (x * z - w * y),     2 * (y * z + w * x),     1 - 2 * (x * x + y * y));

    return mul(Mr, Ms);
}

void CalcCovariance3D(float3x3 RotScale, out float3 Cov3D0, out float3 Cov3D1)
{
    float3x3 Sigma = mul(RotScale, transpose(RotScale));
    Cov3D0 = float3(Sigma._m00, Sigma._m01, Sigma._m02);
    Cov3D1 = float3(Sigma._m11, Sigma._m12, Sigma._m22);
}

float3x3 MakeFloat3x3FromRows(float3 Row0, float3 Row1, float3 Row2)
{
    return float3x3(
        Row0.x, Row0.y, Row0.z,
        Row1.x, Row1.y, Row1.z,
        Row2.x, Row2.y, Row2.z);
}

float3 CalcCovariance2D(
    float3 WorldPos,
    float3 Cov3D0,
    float3 Cov3D1,
    float4x4 ViewMatrix,
    float4x4 ProjectionMatrix,
    float2 ViewSize)
{
    float3 viewPos = mul(float4(WorldPos, 1.0), ViewMatrix).xyz;
    float safeZ = max(abs(viewPos.z), 1e-4);
    float invZ = rcp(safeZ);
    float invZ2 = invZ * invZ;
    float focalX = abs(ViewSize.x * ProjectionMatrix[0][0] * 0.5);
    float focalY = abs(ViewSize.y * ProjectionMatrix[1][1] * 0.5);

    float3x3 J = MakeFloat3x3FromRows(
        float3(focalX * invZ, 0.0, -focalX * viewPos.x * invZ2),
        float3(0.0, focalY * invZ, -focalY * viewPos.y * invZ2),
        float3(0.0, 0.0, 0.0));

    float3x3 V = MakeFloat3x3FromRows(
        float3(Cov3D0.x, Cov3D0.y, Cov3D0.z),
        float3(Cov3D0.y, Cov3D1.x, Cov3D1.y),
        float3(Cov3D0.z, Cov3D1.y, Cov3D1.z));
    float3x3 W = (float3x3)ViewMatrix;
    float3x3 T = mul(J, W);
    float3x3 Cov = mul(T, mul(V, transpose(T)));

    Cov[0][0] += 0.3;
    Cov[1][1] += 0.3;
    return float3(Cov[0][0], Cov[0][1], Cov[1][1]);
}

float3 CalcConic(float3 Cov2D)
{
    float det = Cov2D.x * Cov2D.z - Cov2D.y * Cov2D.y;
    return float3(Cov2D.z, -Cov2D.y, Cov2D.x) * rcp(max(det, 1e-8));
}

float CalcPowerFromConic(float3 Conic, float2 Delta)
{
    return -0.5 * (Conic.x * Delta.x * Delta.x + Conic.z * Delta.y * Delta.y) + Conic.y * Delta.x * Delta.y;
}

#endif
